### ISSUE TITLE
Move macros to correct file

### ISSUE THREAD

**Issue by AtomToast** [codeuniversity/rocket-from-scratch#19]
During restructuring of the files the PRINT_VALUE and PRINTLN_VALUE macros were moved at the bottom of the sd.h. Instead they should be put at the top of sensors.h, where they are actually used

**Comment by Urhengulas** [comment]
I though `sd.h` would be more suited, since the macros depend on `DATA_FILE`, which is sd related.
https://github.com/codeuniversity/rocket-from-scratch/blob/871d35b13c6ef458bdc22aad4571b0249bdad915/main/sd.h#L52-L60

But you can move it if you want :)

**Comment by AtomToast** [comment]
Hm, that's a fair consideration. I just did not expect them there when looking for them. Also having them defined at the bottom of the file feels kinda odd.
@anarchuser what do you say?

**Comment by anarchuser** [comment]
they do belong at the top of the file, below includes.
I think they do make sense in sd.h, though, as they are tools for writing to files on the sd card, not primarily for logging sensor data
